# This file is generated by gyp; do not edit.

include $(CLEAR_VARS)

LOCAL_MODULE_CLASS := STATIC_LIBRARIES
LOCAL_MODULE := spdylay_libspdy_gyp
LOCAL_MODULE_SUFFIX := .a
LOCAL_MODULE_TAGS := optional
gyp_intermediate_dir := $(call local-intermediates-dir)
gyp_shared_intermediate_dir := $(call intermediates-dir-for,GYP,shared)

# Make sure our deps are built first.
GYP_TARGET_DEPENDENCIES :=

GYP_GENERATED_OUTPUTS :=

# Make sure our deps and generated files are built first.
LOCAL_ADDITIONAL_DEPENDENCIES := $(GYP_TARGET_DEPENDENCIES) $(GYP_GENERATED_OUTPUTS)

LOCAL_GENERATED_SOURCES :=

GYP_COPIED_SOURCE_ORIGIN_DIRS :=

LOCAL_SRC_FILES := \
	spdylay/lib/spdylay_buffer.c \
	spdylay/lib/spdylay_client_cert_vector.c \
	spdylay/lib/spdylay_frame.c \
	spdylay/lib/spdylay_gzip.c \
	spdylay/lib/spdylay_helper.c \
	spdylay/lib/spdylay_map.c \
	spdylay/lib/spdylay_npn.c \
	spdylay/lib/spdylay_outbound_item.c \
	spdylay/lib/spdylay_pq.c \
	spdylay/lib/spdylay_queue.c \
	spdylay/lib/spdylay_session.c \
	spdylay/lib/spdylay_stream.c \
	spdylay/lib/spdylay_submit.c \
	spdylay/lib/spdylay_zlib.c


# Flags passed to both C and C++ files.
MY_CFLAGS :=

MY_CFLAGS_C :=

MY_DEFS := \
	'-DANDROID' \
	'-DHAVE_ARPA_INET_H=0' \
	'-DHAVE_DLFCN_H=0' \
	'-DHAVE_INTTYPES_H=0' \
	'-DHAVE_LIBXML2=0'

LOCAL_CFLAGS := $(MY_CFLAGS_C) $(MY_CFLAGS) $(MY_DEFS)

# Include paths placed before CFLAGS/CPPFLAGS
LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)/spdylay/lib \
	$(LOCAL_PATH)/spdylay/lib/includes \
	$(LOCAL_PATH)/spdylay

LOCAL_C_INCLUDES := $(GYP_COPIED_SOURCE_ORIGIN_DIRS) $(LOCAL_C_INCLUDES)

# Flags passed to only C++ (and not C) files.
LOCAL_CPPFLAGS :=

### Rules for final target.

LOCAL_LDFLAGS :=


LOCAL_STATIC_LIBRARIES :=

# Enable grouping to fix circular references
LOCAL_GROUP_STATIC_LIBRARIES := true

LOCAL_SHARED_LIBRARIES :=

# Add target alias to "gyp_all_modules" target.
.PHONY: gyp_all_modules
gyp_all_modules: spdylay_libspdy_gyp

# Alias gyp target name.
.PHONY: libspdy
libspdy: spdylay_libspdy_gyp

include $(BUILD_STATIC_LIBRARY)
